---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocdtest
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v2.1.1-go-1.14
          command:
            - /bin/sh
            - -c
          args:
            - echo "Installing KSOPS..."; export PKG_NAME=ksops; mv
              ${PKG_NAME}.so /custom-tools/; mv $GOPATH/bin/kustomize
              /custom-tools/; echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      serviceAccountName: gke-argocd-demo
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so
              name: custom-tools
              subPath: ksops.so
          env:
            - name: XDG_CONFIG_HOME
              value: /.config
